stones = {
    "Gengarite": {"species": "Gengar", "mega": "Gengar-Mega"},
    "Gardevoirite": {"species": "Gardevoir", "mega": "Gardevoir-Mega"},
    "Ampharosite": {"species": "Ampharos", "mega": "Ampharos-Mega"},
    "Venusaurite": {"species": "Venusaur", "mega": "Venusaur-Mega"},
    "Charizardite X": {"species": "Charizard", "mega": "Charizard-Mega-X"},
    "Blastoisinite": {"species": "Blastoise", "mega": "Blastoise-Mega"},
    "Mewtwonite X": {"species": "Mewtwo", "mega": "Mewtwo-Mega-X"},
    "Mewtwonite Y": {"species": "Mewtwo", "mega": "Mewtwo-Mega-Y"},
    "Blazikenite": {"species": "Blaziken", "mega": "Blaziken-Mega"},
    "Medichamite": {"species": "Medicham", "mega": "Medicham-Mega"},
    "Houndoominite": {"species": "Houndoom", "mega": "Houndoom-Mega"},
    "Aggronite": {"species": "Aggron", "mega": "Aggron-Mega"},
    "Banettite": {"species": "Banette", "mega": "Banette-Mega"},
    "Tyranitarite": {"species": "Tyranitar", "mega": "Tyranitar-Mega"},
    "Scizorite": {"species": "Scizor", "mega": "Scizor-Mega"},
    "Pinsirite": {"species": "Pinsir", "mega": "Pinsir-Mega"},
    "Aerodactylite": {"species": "Aerodactyl", "mega": "Aerodactyl-Mega"},
    "Lucarionite": {"species": "Lucario", "mega": "Lucario-Mega"},
    "Abomasite": {"species": "Abomasnow", "mega": "Abomasnow-Mega"},
    "Kangaskhanite": {"species": "Kangaskhan", "mega": "Kangaskhan-Mega"},
    "Gyaradosite": {"species": "Gyarados", "mega": "Gyarados-Mega"},
    "Absolite": {"species": "Absol", "mega": "Absol-Mega"},
    "Charizardite Y": {"species": "Charizard", "mega": "Charizard-Mega-Y"},
    "Alakazite": {"species": "Alakazam", "mega": "Alakazam-Mega"},
    "Heracronite": {"species": "Heracross", "mega": "Heracross-Mega"},
    "Mawilite": {"species": "Mawile", "mega": "Mawile-Mega"},
    "Manectite": {"species": "Manectric", "mega": "Manectric-Mega"},
    "Garchompite": {"species": "Garchomp", "mega": "Garchomp-Mega"},
    "Latiasite": {"species": "Latias", "mega": "Latias-Mega"},
    "Latiosite": {"species": "Latios", "mega": "Latios-Mega"},
    "Swampertite": {"species": "Swampert", "mega": "Swampert-Mega"},
    "Sceptilite": {"species": "Sceptile", "mega": "Sceptile-Mega"},
    "Sablenite": {"species": "Sableye", "mega": "Sableye-Mega"},
    "Altarianite": {"species": "Altaria", "mega": "Altaria-Mega"},
    "Galladite": {"species": "Gallade", "mega": "Gallade-Mega"},
    "Audinite": {"species": "Audino", "mega": "Audino-Mega"},
    "Metagrossite": {"species": "Metagross", "mega": "Metagross-Mega"},
    "Sharpedonite": {"species": "Sharpedo", "mega": "Sharpedo-Mega"},
    "Slowbronite": {"species": "Slowbro", "mega": "Slowbro-Mega"},
    "Steelixite": {"species": "Steelix", "mega": "Steelix-Mega"},
    "Pidgeotite": {"species": "Pidgeot", "mega": "Pidgeot-Mega"},
    "Glalitite": {"species": "Glalie", "mega": "Glalie-Mega"},
    "Diancite": {"species": "Diancie", "mega": "Diancie-Mega"},
    "Cameruptite": {"species": "Camerupt", "mega": "Camerupt-Mega"},
    "Lopunnite": {"species": "Lopunny", "mega": "Lopunny-Mega"},
    "Salamencite": {"species": "Salamence", "mega": "Salamence-Mega"},
    "Beedrillite": {"species": "Beedrill", "mega": "Beedrill-Mega"},
    "Clefablite": {"species": "Clefable", "mega": "Clefable-Mega"},
    "Victreebelite": {"species": "Victreebel", "mega": "Victreebel-Mega"},
    "Starminite": {"species": "Starmie", "mega": "Starmie-Mega"},
    "Dragoninite": {"species": "Dragonite", "mega": "Dragonite-Mega"},
    "Meganiumite": {"species": "Meganium", "mega": "Meganium-Mega"},
    "Feraligite": {"species": "Feraligatr", "mega": "Feraligatr-Mega"},
    "Skarmorite": {"species": "Skarmory", "mega": "Skarmory-Mega"},
    "Froslassite": {"species": "Froslass", "mega": "Froslass-Mega"},
    "Heatranite": {"species": "Heatran", "mega": "Heatran-Mega"},
    "Darkranite": {"species": "Darkrai", "mega": "Darkrai-Mega"},
    "Emboarite": {"species": "Emboar", "mega": "Emboar-Mega"},
    "Excadrite": {"species": "Excadrill", "mega": "Excadrill-Mega"},
    "Scolipite": {"species": "Scolipede", "mega": "Scolipede-Mega"},
    "Scraftinite": {"species": "Scrafty", "mega": "Scrafty-Mega"},
    "Eelektrossite": {"species": "Eelektross", "mega": "Eelektross-Mega"},
    "Chandelurite": {"species": "Chandelure", "mega": "Chandelure-Mega"},
    "Chesnaughtite": {"species": "Chesnaught", "mega": "Chesnaught-Mega"},
    "Delphoxite": {"species": "Delphox", "mega": "Delphox-Mega"},
    "Greninjite": {"species": "Greninja", "mega": "Greninja-Mega"},
    "Pyroarite": {"species": "Pyroar", "mega": "Pyroar-Mega"},
    "Floettite": {"species": "Floette-Eternal", "mega": "Floette-Mega"},
    "Malamarite": {"species": "Malamar", "mega": "Malamar-Mega"},
    "Barbaracite": {"species": "Barbaracle", "mega": "Barbaracle-Mega"},
    "Dragalgite": {"species": "Dragalge", "mega": "Dragalge-Mega"},
    "Hawluchanite": {"species": "Hawlucha", "mega": "Hawlucha-Mega"},
    "Zygardite": {"species": "Zygarde-Complete", "mega": "Zygarde-Mega"},
    "Drampanite": {"species": "Drampa", "mega": "Drampa-Mega"},
    "Zeraorite": {"species": "Zeraora", "mega": "Zeraora-Mega"},
    "Falinksite": {"species": "Falinks", "mega": "Falinks-Mega"},
    "Raichunite X": {"species": "Raichu", "mega": "Raichu-Mega-X"},
    "Raichunite Y": {"species": "Raichu", "mega": "Raichu-Mega-Y"},
    "Chimechite": {"species": "Chimecho", "mega": "Chimecho-Mega"},
    "Absolite Z": {"species": "Absol", "mega": "Absol-Mega-Z"},
    "Staraptite": {"species": "Staraptor", "mega": "Staraptor-Mega"},
    "Garchompite Z": {"species": "Garchomp", "mega": "Garchomp-Mega-Z"},
    "Lucarionite Z": {"species": "Lucario", "mega": "Lucario-Mega-Z"},
    "Golurkite": {"species": "Golurk", "mega": "Golurk-Mega"},
    "Meowsticite": {"species": "Meowstic", "mega": "Meowstic-M-Mega"},
    "Meowsticite": {"species": "Meowstic-F", "mega": "Meowstic-F-Mega"},
    "Crabominite": {"species": "Crabominable", "mega": "Crabominable-Mega"},
    "Golisopite": {"species": "Golisopod", "mega": "Golisopod-Mega"},
    "Magearnite": {"species": "Magearna", "mega": "Magearna-Mega"},
    "Scovillainite": {"species": "Scovillain", "mega": "Scovillain-Mega"},
    "Baxcalibrite": {"species": "Baxcalibur", "mega": "Baxcalibur-Mega"},
    "Tatsugirinite": {"species": "Tatsugiri", "mega": "Tatsugiri-Curly-Mega"},
    "Tatsugirinite": {"species": "Tatsugiri-Droopy", "mega": "Tatsugiri-Droopy-Mega"},
    "Tatsugirinite": {"species": "Tatsugiri-Stretchy", "mega": "Tatsugiri-Stretchy-Mega"},
    "Glimmoranite": {"species": "Glimmora", "mega": "Glimmora-Mega"}
}

# TODO
moves = {
    "Dragon Ascent": {"species": "Rayquaza", "mega": "Rayquaza-Mega"}
}
