megas = {
    "Gengarite": {"item": "Gengar", "mega": "Gengar-Mega"},
    "Gardevoirite": {"item": "Gardevoir", "mega": "Gardevoir-Mega"},
    "Ampharosite": {"item": "Ampharos", "mega": "Ampharos-Mega"},
    "Venusaurite": {"item": "Venusaur", "mega": "Venusaur-Mega"},
    "Charizardite X": {"item": "Charizard", "mega": "Charizard-Mega-X"},
    "Blastoisinite": {"item": "Blastoise", "mega": "Blastoise-Mega"},
    "Mewtwonite X": {"item": "Mewtwo", "mega": "Mewtwo-Mega-X"},
    "Mewtwonite Y": {"item": "Mewtwo", "mega": "Mewtwo-Mega-Y"},
    "Blazikenite": {"item": "Blaziken", "mega": "Blaziken-Mega"},
    "Medichamite": {"item": "Medicham", "mega": "Medicham-Mega"},
    "Houndoominite": {"item": "Houndoom", "mega": "Houndoom-Mega"},
    "Aggronite": {"item": "Aggron", "mega": "Aggron-Mega"},
    "Banettite": {"item": "Banette", "mega": "Banette-Mega"},
    "Tyranitarite": {"item": "Tyranitar", "mega": "Tyranitar-Mega"},
    "Scizorite": {"item": "Scizor", "mega": "Scizor-Mega"},
    "Pinsirite": {"item": "Pinsir", "mega": "Pinsir-Mega"},
    "Aerodactylite": {"item": "Aerodactyl", "mega": "Aerodactyl-Mega"},
    "Lucarionite": {"item": "Lucario", "mega": "Lucario-Mega"},
    "Abomasite": {"item": "Abomasnow", "mega": "Abomasnow-Mega"},
    "Kangaskhanite": {"item": "Kangaskhan", "mega": "Kangaskhan-Mega"},
    "Gyaradosite": {"item": "Gyarados", "mega": "Gyarados-Mega"},
    "Absolite": {"item": "Absol", "mega": "Absol-Mega"},
    "Charizardite Y": {"item": "Charizard", "mega": "Charizard-Mega-Y"},
    "Alakazite": {"item": "Alakazam", "mega": "Alakazam-Mega"},
    "Heracronite": {"item": "Heracross", "mega": "Heracross-Mega"},
    "Mawilite": {"item": "Mawile", "mega": "Mawile-Mega"},
    "Manectite": {"item": "Manectric", "mega": "Manectric-Mega"},
    "Garchompite": {"item": "Garchomp", "mega": "Garchomp-Mega"},
    "Latiasite": {"item": "Latias", "mega": "Latias-Mega"},
    "Latiosite": {"item": "Latios", "mega": "Latios-Mega"},
    "Swampertite": {"item": "Swampert", "mega": "Swampert-Mega"},
    "Sceptilite": {"item": "Sceptile", "mega": "Sceptile-Mega"},
    "Sablenite": {"item": "Sableye", "mega": "Sableye-Mega"},
    "Altarianite": {"item": "Altaria", "mega": "Altaria-Mega"},
    "Galladite": {"item": "Gallade", "mega": "Gallade-Mega"},
    "Audinite": {"item": "Audino", "mega": "Audino-Mega"},
    "Metagrossite": {"item": "Metagross", "mega": "Metagross-Mega"},
    "Sharpedonite": {"item": "Sharpedo", "mega": "Sharpedo-Mega"},
    "Slowbronite": {"item": "Slowbro", "mega": "Slowbro-Mega"},
    "Steelixite": {"item": "Steelix", "mega": "Steelix-Mega"},
    "Pidgeotite": {"item": "Pidgeot", "mega": "Pidgeot-Mega"},
    "Glalitite": {"item": "Glalie", "mega": "Glalie-Mega"},
    "Diancite": {"item": "Diancie", "mega": "Diancie-Mega"},
    "Cameruptite": {"item": "Camerupt", "mega": "Camerupt-Mega"},
    "Lopunnite": {"item": "Lopunny", "mega": "Lopunny-Mega"},
    "Salamencite": {"item": "Salamence", "mega": "Salamence-Mega"},
    "Beedrillite": {"item": "Beedrill", "mega": "Beedrill-Mega"},
    "Clefablite": {"item": "Clefable", "mega": "Clefable-Mega"},
    "Victreebelite": {"item": "Victreebel", "mega": "Victreebel-Mega"},
    "Starminite": {"item": "Starmie", "mega": "Starmie-Mega"},
    "Dragoninite": {"item": "Dragonite", "mega": "Dragonite-Mega"},
    "Meganiumite": {"item": "Meganium", "mega": "Meganium-Mega"},
    "Feraligite": {"item": "Feraligatr", "mega": "Feraligatr-Mega"},
    "Skarmorite": {"item": "Skarmory", "mega": "Skarmory-Mega"},
    "Froslassite": {"item": "Froslass", "mega": "Froslass-Mega"},
    "Heatranite": {"item": "Heatran", "mega": "Heatran-Mega"},
    "Darkranite": {"item": "Darkrai", "mega": "Darkrai-Mega"},
    "Emboarite": {"item": "Emboar", "mega": "Emboar-Mega"},
    "Excadrite": {"item": "Excadrill", "mega": "Excadrill-Mega"},
    "Scolipite": {"item": "Scolipede", "mega": "Scolipede-Mega"},
    "Scraftinite": {"item": "Scrafty", "mega": "Scrafty-Mega"},
    "Eelektrossite": {"item": "Eelektross", "mega": "Eelektross-Mega"},
    "Chandelurite": {"item": "Chandelure", "mega": "Chandelure-Mega"},
    "Chesnaughtite": {"item": "Chesnaught", "mega": "Chesnaught-Mega"},
    "Delphoxite": {"item": "Delphox", "mega": "Delphox-Mega"},
    "Greninjite": {"item": "Greninja", "mega": "Greninja-Mega"},
    "Pyroarite": {"item": "Pyroar", "mega": "Pyroar-Mega"},
    "Floettite": {"item": "Floette-Eternal", "mega": "Floette-Mega"},
    "Malamarite": {"item": "Malamar", "mega": "Malamar-Mega"},
    "Barbaracite": {"item": "Barbaracle", "mega": "Barbaracle-Mega"},
    "Dragalgite": {"item": "Dragalge", "mega": "Dragalge-Mega"},
    "Hawluchanite": {"item": "Hawlucha", "mega": "Hawlucha-Mega"},
    "Zygardite": {"item": "Zygarde-Complete", "mega": "Zygarde-Mega"},
    "Drampanite": {"item": "Drampa", "mega": "Drampa-Mega"},
    "Zeraorite": {"item": "Zeraora", "mega": "Zeraora-Mega"},
    "Falinksite": {"item": "Falinks", "mega": "Falinks-Mega"},
    "Raichunite X": {"item": "Raichu", "mega": "Raichu-Mega-X"},
    "Raichunite Y": {"item": "Raichu", "mega": "Raichu-Mega-Y"},
    "Chimechite": {"item": "Chimecho", "mega": "Chimecho-Mega"},
    "Absolite Z": {"item": "Absol", "mega": "Absol-Mega-Z"},
    "Staraptite": {"item": "Staraptor", "mega": "Staraptor-Mega"},
    "Garchompite Z": {"item": "Garchomp", "mega": "Garchomp-Mega-Z"},
    "Lucarionite Z": {"item": "Lucario", "mega": "Lucario-Mega-Z"},
    "Golurkite": {"item": "Golurk", "mega": "Golurk-Mega"},
    "Meowsticite": {"item": "Meowstic", "mega": "Meowstic-M-Mega"},
    "Meowsticite": {"item": "Meowstic-F", "mega": "Meowstic-F-Mega"},
    "Crabominite": {"item": "Crabominable", "mega": "Crabominable-Mega"},
    "Golisopite": {"item": "Golisopod", "mega": "Golisopod-Mega"},
    "Magearnite": {"item": "Magearna", "mega": "Magearna-Mega"},
    "Scovillainite": {"item": "Scovillain", "mega": "Scovillain-Mega"},
    "Baxcalibrite": {"item": "Baxcalibur", "mega": "Baxcalibur-Mega"},
    "Tatsugirinite": {"item": "Tatsugiri", "mega": "Tatsugiri-Curly-Mega"},
    "Tatsugirinite": {"item": "Tatsugiri-Droopy", "mega": "Tatsugiri-Droopy-Mega"},
    "Tatsugirinite": {"item": "Tatsugiri-Stretchy", "mega": "Tatsugiri-Stretchy-Mega"},
    "Glimmoranite": {"item": "Glimmora", "mega": "Glimmora-Mega"},
    "Rayquaza": {"move": "Dragon Ascent", "mega": "Rayquaza-Mega"}
}

