CREATE TABLE format(
  id text PRIMARY KEY,
  name text NOT NULL,
  gscup boolean NOT NULL,
  megaevolution boolean NOT NULL,
  terastal boolean NOT NULL
);

CREATE TABLE season_formats(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  season integer NOT NULL,
  format_id text NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL
);

CREATE TABLE tournament(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  season integer NOT NULL,
  season_format integer NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  kicker integer NOT NULL,
  day2 integer,
  cut integer
);

CREATE TABLE team(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tour_id integer NOT NULL,
  name text NOT NULL,
  wins smallint NOT NULL,
  losses smallint NOT NULL,
  ties smallint NOT NULL,
  place smallint NOT NULL,
  top smallint,
  paste character(16)
);

CREATE TABLE team_pokemon(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team_id uuid NOT NULL,
  species text NOT NULL,
  item text,
  ability text NOT NULL
);

CREATE TABLE pokemon_moves(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pokemon_id integer NOT NULL,
  move text NOT NULL
);

CREATE TABLE pokemon_teratypes(
  pokemon_id integer PRIMARY KEY,
  teratype text NOT NULL
);

-- copy from existing CSVs generated from the top cut explorer...
-- COPY format FROM '/tmp/tmp.pvzDvQzQ1g/format.csv' WITH (FORMAT csv, HEADER true);
-- COPY season_formats FROM '/tmp/tmp.pvzDvQzQ1g/season_formats.csv' WITH (FORMAT csv, HEADER true);
-- COPY tournament FROM '/tmp/tmp.pvzDvQzQ1g/tournament.csv' WITH (FORMAT csv, HEADER true);
-- COPY team FROM '/tmp/tmp.pvzDvQzQ1g/team.csv' WITH (FORMAT csv, HEADER true);
-- COPY team_pokemon FROM '/tmp/tmp.pvzDvQzQ1g/team_pokemon.csv' WITH (FORMAT csv, HEADER true);
-- COPY pokemon_moves FROM '/tmp/tmp.pvzDvQzQ1g/pokemon_moves.csv' WITH (FORMAT csv, HEADER true);
-- COPY pokemon_teratypes FROM '/tmp/tmp.pvzDvQzQ1g/pokemon_teratypes.csv' WITH (FORMAT csv, HEADER true);

ALTER TABLE season_formats ADD FOREIGN KEY (format_id) REFERENCES format;
ALTER TABLE tournament ADD FOREIGN KEY (season_format) REFERENCES season_formats;
ALTER TABLE tournament ADD CONSTRAINT season_slug UNIQUE(season, slug);
ALTER TABLE team ADD FOREIGN KEY (tour_id) REFERENCES tournament ON DELETE CASCADE;
ALTER TABLE team_pokemon ADD FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE;
ALTER TABLE pokemon_moves ADD FOREIGN KEY (pokemon_id) REFERENCES team_pokemon ON DELETE CASCADE;
ALTER TABLE pokemon_teratypes ADD FOREIGN KEY (pokemon_id) REFERENCES team_pokemon ON DELETE CASCADE;

SELECT setval('season_formats_id_seq', (SELECT MAX(id) FROM season_formats));
SELECT setval('tournament_id_seq', (SELECT MAX(id) FROM tournament));
SELECT setval('team_pokemon_id_seq', (SELECT MAX(id) FROM team_pokemon));
SELECT setval('pokemon_moves_id_seq', (SELECT MAX(id) FROM pokemon_moves));

